# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j_aCr3OwBBcfzUUGto_PvMDECkKCv1OB
"""

import re

class Dummy3_Sentence_Splitter(Sentence_Splitter):
     
     def splitter(self, text):
       res = [x for x in re.split("[//.|//!|//?]", text) if x!=""]
       return res


D = Dummy3_Sentence_Splitter()
h = D.splitter(text)
print(h)