# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j_aCr3OwBBcfzUUGto_PvMDECkKCv1OB
"""

class Dummy_Sentence_Splitter(Sentence_Splitter):

    def splitter(self, text):
        text_1 = text.split(".")
        return text_1

R = Dummy_Sentence_Splitter()
x = R.splitter(text)
print(x)