# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j_aCr3OwBBcfzUUGto_PvMDECkKCv1OB
"""

from gensim.summarization.summarizer import summarize

class Gensim_Summarizer(Summarizer):

   def summarizer(self, text):
     gensim_summary = summarize(text, ratio = 0.2)      
     return gensim_summary


T = Gensim_Summarizer()
summary_gensim = T.summarizer(text)
print(summary_gensim)