# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j_aCr3OwBBcfzUUGto_PvMDECkKCv1OB
"""

class Sentence_Splitter(ABC):
    
     @abstractmethod
     def splitter(self, text):
         pass

class Summarizer(ABC):
    
     @abstractmethod
     def summarizer(self):
         pass